FROM php:8.1-apache-bookworm

RUN apt-get update -y && apt-get install -y \
    unzip \
    libfreetype-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libzip-dev

RUN docker-php-ext-install pdo pdo_mysql mysqli

RUN docker-php-ext-configure gd \
    --with-freetype \
    --with-jpeg

RUN docker-php-ext-install -j$(nproc) gd zip

RUN a2enmod rewrite

RUN sed -i 's#DocumentRoot /var/www/html#DocumentRoot /var/www/html/src#' \
    /etc/apache2/sites-available/000-default.conf

RUN sed -i 's#<Directory /var/www/>#<Directory /var/www/html/src/>#' \
    /etc/apache2/apache2.conf

RUN sed -i 's/AllowOverride None/AllowOverride All/g' \
    /etc/apache2/apache2.conf

COPY php.ini /usr/local/etc/php/

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80